/* Quản lý lớp - frontend GitHub Pages. Không chứa secret. */
const CFG = window.LMS_CONFIG || {};
const API = CFG.API_URL || '';
const state = {
  token: localStorage.getItem('lms_token') || '',
  user: JSON.parse(localStorage.getItem('lms_user') || 'null'),
  roleTab: 'student', data: null, activeTab: null, classId: null,
  selectedSubjectId: null, selectedAssignment: null, selectedSubmission: null,
  selectedStudents: new Set(), adminPage: 1, adminRoleFilter: '', busy: false
};
const $ = s => document.querySelector(s);
const app = () => $('#app');
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const jparse = (v, fallback=[]) => { try{return typeof v==='string'?JSON.parse(v):v ?? fallback}catch{return fallback} };
function toast(message,type='ok'){ const el=$('#toast'); el.textContent=message; el.hidden=false; el.className='toast'+(type==='error'?' error':''); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.hidden=true,2600); }
function setBusy(v){state.busy=v; document.querySelectorAll('[data-busy]').forEach(b=>b.disabled=v)}
function saveSession(){ if(state.token)localStorage.setItem('lms_token',state.token); else localStorage.removeItem('lms_token'); if(state.user)localStorage.setItem('lms_user',JSON.stringify(state.user)); else localStorage.removeItem('lms_user'); }
// Bridge GitHub -> Apps Script V1.2: POST form ẩn, không dùng fetch/CORS.
const BRIDGE_CHANNEL='lms-gas-form-v2';
const bridgePending=new Map();
window.addEventListener('message',(ev)=>{
  const m=ev.data||{};
  if(m.channel!==BRIDGE_CHANNEL || !m.id || !bridgePending.has(m.id)) return;
  const q=bridgePending.get(m.id); bridgePending.delete(m.id);
  q.cleanup();
  q.resolve(m.result);
});
function bridgeCall(payload){
  return new Promise((resolve,reject)=>{
    if(!API || API.includes('PASTE_')){reject(new Error('Chưa cấu hình URL Apps Script trong config.js'));return;}
    const id='rpc_'+Date.now()+'_'+Math.random().toString(36).slice(2);
    const frameName='lms_bridge_'+id.replace(/[^a-zA-Z0-9_]/g,'');
    const iframe=document.createElement('iframe');
    iframe.name=frameName;
    iframe.setAttribute('aria-hidden','true');
    iframe.tabIndex=-1;
    iframe.style.cssText='position:fixed;width:1px;height:1px;opacity:0;pointer-events:none;border:0;left:-9999px;top:-9999px';
    document.body.appendChild(iframe);

    const form=document.createElement('form');
    form.method='POST';
    form.action=API;
    form.target=frameName;
    form.style.display='none';
    const add=(name,value)=>{const i=document.createElement('input');i.type='hidden';i.name=name;i.value=value;form.appendChild(i)};
    add('bridge','1');
    add('requestId',id);
    add('payload',JSON.stringify(payload));
    document.body.appendChild(form);

    const cleanup=()=>{try{form.remove()}catch{};try{iframe.remove()}catch{};clearTimeout(timer)};
    const timer=setTimeout(()=>{
      if(bridgePending.has(id)) bridgePending.delete(id);
      cleanup();
      reject(new Error('Máy chủ phản hồi quá lâu. Kiểm tra phiên bản Apps Script V1.2.'));
    },30000);
    bridgePending.set(id,{resolve,reject,cleanup});
    try{form.submit();setTimeout(()=>{try{form.remove()}catch{}},1000)}catch(err){bridgePending.delete(id);cleanup();reject(err)}
  });
}
async function rpc(action,data={}){
  if(!API || API.includes('PASTE_')) throw new Error('Chưa cấu hình URL Apps Script trong config.js');
  let out;
  try{out=await bridgeCall({action,token:state.token,...data});}
  catch(e){throw new Error(e.message||'Không kết nối được máy chủ.');}
  if(!out || typeof out!=='object') throw new Error('Máy chủ trả dữ liệu không hợp lệ.');
  if(!out.success){ if(out.code==='SESSION_EXPIRED'){state.token='';state.user=null;saveSession();renderLogin();} throw new Error(out.message||'Có lỗi xảy ra'); }
  return out.data;
}
function roleLabel(r){return r==='admin'?'Admin':r==='teacher'?'Giáo viên':'Học sinh'}
function icon(t){const map={book:'📚',bell:'🔔',user:'👤',users:'👥',chart:'📊',folder:'📁',award:'🏆',home:'🏠',gear:'⚙️',plus:'＋',send:'➤'};return map[t]||'•'}
function header(title,subtitle,nav=[]){return `<header class="header"><div class="container"><div class="header-main"><div class="brand"><div class="brand-icon">${icon('award')}</div><div><h1>${esc(title)}</h1><p>${subtitle||'Bảng điều khiển'}</p></div></div><button class="icon-btn" onclick="logout()" title="Đăng xuất">↪</button></div>${nav.length?`<div class="nav-scroll">${nav.map(n=>`<button class="nav-btn ${state.activeTab===n.id?'active':''}" onclick="switchTab('${n.id}')">${n.icon||''} ${esc(n.label)}</button>`).join('')}</div>`:''}</div></header>`}
function renderLogin(){
  state.data=null; state.activeTab=null;
  app().innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-logo">🎓</div><h1 class="login-title">${esc(CFG.APP_NAME||'QUẢN LÝ LỚP')}</h1><p class="center muted small">Hệ thống thi đua, giao bài & quản lý lớp</p><div class="role-tabs">${['student','teacher','admin'].map(r=>`<button class="${state.roleTab===r?'active':''}" onclick="chooseRole('${r}')">${roleLabel(r)}</button>`).join('')}</div><form id="loginForm" class="grid"><div class="field"><label>Tên đăng nhập</label><input class="input" id="username" autocomplete="username" required placeholder="Ví dụ: minh01" /></div><div class="field"><label>Mã PIN / Mật khẩu</label><input class="input" id="password" type="password" autocomplete="current-password" required placeholder="••••••" /></div><button class="btn btn-primary btn-block" data-busy>ĐĂNG NHẬP</button></form><p class="center tiny muted" style="margin-top:14px">Dùng cùng một link trên điện thoại, máy tính bảng và máy tính.</p></div></div>`;
  $('#loginForm').onsubmit=login;
}
function chooseRole(r){state.roleTab=r;renderLogin()}
async function login(e){e.preventDefault();setBusy(true);try{const data=await rpc('login',{username:$('#username').value.trim(),password:$('#password').value,expectedRole:state.roleTab});state.token=data.token;state.user=data.user;saveSession();toast('Đăng nhập thành công');await bootstrap();}catch(err){toast(err.message,'error')}finally{setBusy(false)}}
async function logout(){try{if(state.token)await rpc('logout')}catch{}state.token='';state.user=null;state.data=null;saveSession();renderLogin()}
async function bootstrap(force=false){
  if(!state.token){renderLogin();return}
  app().innerHTML=`<div class="login-wrap"><div style="width:min(430px,90%)"><div class="skeleton"></div><div style="height:12px"></div><div class="skeleton"></div></div></div>`;
  try{state.data=await rpc('bootstrap',{force});state.user=state.data.user;saveSession(); if(state.user.role==='admin'){state.activeTab=state.activeTab||'overview';renderAdmin()}else if(state.user.role==='teacher'){state.classId=state.classId||state.data.classes?.[0]?.id||'';state.activeTab=state.activeTab||'assignments';renderTeacher()}else{state.activeTab=state.activeTab||'assignments';renderStudent()}}catch(err){toast(err.message,'error');if(!state.user)renderLogin()}
}
function switchTab(id){state.activeTab=id;state.selectedSubjectId=null;state.selectedAssignment=null;if(state.user.role==='admin')renderAdmin();else if(state.user.role==='teacher')renderTeacher();else renderStudent()}
function classSelect(){const list=state.data.classes||[];return list.length>1?`<select class="select" style="width:auto;min-width:120px;padding:8px 12px" onchange="changeTeacherClass(this.value)">${list.map(c=>`<option value="${c.id}" ${c.id===state.classId?'selected':''}>${esc(c.name)}</option>`).join('')}</select>`:`<span class="pill blue">${esc(list[0]?.name||'Chưa có lớp')}</span>`}
async function changeTeacherClass(id){state.classId=id;state.selectedSubjectId=null;try{state.data.classData=await rpc('teacher.classData',{classId:id});renderTeacher()}catch(e){toast(e.message,'error')}}

// ADMIN
function renderAdmin(){const d=state.data;const nav=[['overview','🏠','Tổng quan'],['classes','🏫','Lớp học'],['users','👥','Tài khoản'],['permissions','🔐','Phân quyền'],['subjects','📚','Môn học']].map(x=>({id:x[0],icon:x[1],label:x[2]}));let content='';if(state.activeTab==='overview')content=adminOverview();if(state.activeTab==='classes')content=adminClasses();if(state.activeTab==='users')content=adminUsers();if(state.activeTab==='permissions')content=adminPermissions();if(state.activeTab==='subjects')content=adminSubjects();app().innerHTML=`<div class="app-shell">${header('Quản trị hệ thống',state.user.displayName,nav)}<main><div class="container">${content}</div></main></div>`}
function adminOverview(){const x=state.data.stats||{};return `<div class="grid grid-4"><div class="stat"><b>${x.teachers||0}</b><span>Giáo viên</span></div><div class="stat"><b>${x.students||0}</b><span>Học sinh</span></div><div class="stat"><b>${x.classes||0}</b><span>Lớp học</span></div><div class="stat"><b>${x.assignments||0}</b><span>Bài tập đang hoạt động</span></div></div><div class="card" style="margin-top:16px"><div class="section-title"><div><h2>Thao tác nhanh</h2><p>Tạo dữ liệu nền cho hệ thống.</p></div></div><div class="grid grid-3"><button class="btn btn-soft" onclick="openCreateUser('teacher')">＋ Giáo viên</button><button class="btn btn-soft" onclick="openCreateUser('student')">＋ Học sinh</button><button class="btn btn-soft" onclick="openCreateClass()">＋ Lớp học</button></div></div>`}
function adminClasses(){const cs=state.data.classes||[];return `<div class="section-title"><div><h2>Lớp học</h2><p>Quản lý nhiều lớp trên cùng một hệ thống.</p></div><button class="btn btn-primary" onclick="openCreateClass()">＋ Tạo lớp</button></div><div class="grid grid-3">${cs.map(c=>`<div class="card card-flat"><div class="subject-icon">🏫</div><h3>${esc(c.name)}</h3><p class="muted small">Khối ${esc(c.grade||'')} · ${esc(c.academicYear||'')}</p><div style="margin-top:12px"><span class="pill ${c.status==='active'?'green':''}">${esc(c.status||'active')}</span></div></div>`).join('')||'<div class="card center muted">Chưa có lớp.</div>'}</div>`}
function adminUsers(){const u=state.data.userPage||{items:[],page:1,total:0,pageSize:50};return `<div class="section-title"><div><h2>Tài khoản</h2><p>Chỉ tải tối đa 50 tài khoản mỗi trang để giữ tốc độ tốt.</p></div><button class="btn btn-primary" onclick="openCreateUser('student')">＋ Tạo tài khoản</button></div><div class="card"><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px"><select class="select" style="width:auto" onchange="loadAdminUsers(1,this.value)"><option value="">Tất cả vai trò</option><option value="teacher">Giáo viên</option><option value="student">Học sinh</option><option value="admin">Admin</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Họ tên</th><th>Username</th><th>Vai trò</th><th>Trạng thái</th><th></th></tr></thead><tbody>${u.items.map(x=>`<tr><td><b>${esc(x.displayName)}</b></td><td>${esc(x.username)}</td><td>${roleLabel(x.role)}</td><td><span class="pill ${x.status==='active'?'green':'red'}">${esc(x.status)}</span></td><td><button class="btn btn-soft" onclick="resetPassword('${x.id}','${esc(x.username)}')">Reset PIN</button></td></tr>`).join('')}</tbody></table></div><div class="pager"><span class="small muted">${u.total} tài khoản</span><button class="btn btn-soft" ${u.page<=1?'disabled':''} onclick="loadAdminUsers(${u.page-1})">Trước</button><span class="pill">Trang ${u.page}</span><button class="btn btn-soft" ${u.page*u.pageSize>=u.total?'disabled':''} onclick="loadAdminUsers(${u.page+1})">Sau</button></div></div>`}
async function loadAdminUsers(page=1,role=state.adminRoleFilter){state.adminRoleFilter=role||'';try{state.data.userPage=await rpc('admin.listUsers',{page,role:state.adminRoleFilter});state.activeTab='users';renderAdmin()}catch(e){toast(e.message,'error')}}
function adminPermissions(){const teachers=state.data.teachers||[];return `<div class="section-title"><div><h2>Phân quyền giáo viên</h2><p>Phân lớp, môn và quyền theo từng lớp.</p></div></div><div class="card"><div class="field"><label>Chọn giáo viên</label><select class="select" onchange="loadTeacherPermissions(this.value)"><option value="">-- Chọn giáo viên --</option>${teachers.map(t=>`<option value="${t.id}">${esc(t.displayName)}</option>`).join('')}</select></div><div id="permArea" style="margin-top:14px" class="muted small">Chọn giáo viên để xem quyền.</div></div>`}
async function loadTeacherPermissions(teacherId){if(!teacherId){$('#permArea').innerHTML='Chọn giáo viên để xem quyền.';return}try{const data=await rpc('admin.teacherAssignments',{teacherId});const classes=state.data.classes||[];const subjects=state.data.subjects||[];$('#permArea').innerHTML=`<div class="grid">${classes.map(c=>{const a=data.find(x=>x.classId===c.id);const p=jparse(a?.permissions,{});const sids=jparse(a?.subjectIds,[]);return `<div class="card card-flat"><b>${esc(c.name)}</b><div class="form-grid" style="margin-top:10px"><div class="field"><label>Môn được dạy</label><select multiple class="select" id="sub_${c.id}" style="min-height:90px">${subjects.map(s=>`<option value="${s.id}" ${sids.includes(s.id)?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Quyền</label><label><input type="checkbox" id="ca_${c.id}" ${p.createAssignments?'checked':''}> Giao bài</label><label><input type="checkbox" id="gr_${c.id}" ${p.gradeSubmissions?'checked':''}> Chấm bài</label><label><input type="checkbox" id="an_${c.id}" ${p.sendAnnouncements?'checked':''}> Thông báo</label><label><input type="checkbox" id="bp_${c.id}" ${p.manageBehaviorPoints?'checked':''}> Thi đua</label></div></div><button class="btn btn-primary" style="margin-top:10px" onclick="saveTeacherAssignment('${teacherId}','${c.id}')">Lưu lớp ${esc(c.name)}</button></div>`}).join('')}</div>`}catch(e){toast(e.message,'error')}}
async function saveTeacherAssignment(teacherId,classId){const subjectIds=Array.from($(`#sub_${classId}`).selectedOptions).map(o=>o.value);const permissions={viewStudents:true,createAssignments:$(`#ca_${classId}`).checked,viewSubmissions:true,gradeSubmissions:$(`#gr_${classId}`).checked,sendAnnouncements:$(`#an_${classId}`).checked,manageBehaviorPoints:$(`#bp_${classId}`).checked};try{await rpc('admin.assignTeacher',{teacherId,classId,subjectIds,permissions});toast('Đã lưu phân quyền')}catch(e){toast(e.message,'error')}}
function adminSubjects(){return `<div class="section-title"><div><h2>Môn học</h2><p>Danh mục dùng chung cho các lớp.</p></div><button class="btn btn-primary" onclick="openCreateSubject()">＋ Môn học</button></div><div class="subject-grid">${(state.data.subjects||[]).map(s=>`<div class="subject-card"><div class="subject-icon">📁</div><h3>${esc(s.name)}</h3><p>${esc(s.status||'active')}</p></div>`).join('')}</div>`}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><b>Thiết lập</b><button class="close" onclick="closeModal()">×</button></div><div class="modal-body">${html}</div></div></div>`)}function closeModal(){document.querySelector('#modal')?.remove()}
function openCreateClass(){modal(`<form id="mform" class="grid"><div class="field"><label>Tên lớp</label><input class="input" name="name" required placeholder="2A"></div><div class="form-grid"><div class="field"><label>Khối</label><input class="input" name="grade" required placeholder="2"></div><div class="field"><label>Năm học</label><input class="input" name="academicYear" value="2026-2027" required></div></div><button class="btn btn-primary">Tạo lớp</button></form>`);$('#mform').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await rpc('admin.createClass',Object.fromEntries(f));closeModal();toast('Đã tạo lớp');await bootstrap(true)}catch(x){toast(x.message,'error')}}}
function openCreateUser(role='student'){modal(`<form id="mform" class="grid"><div class="form-grid"><div class="field"><label>Họ tên</label><input class="input" name="displayName" required></div><div class="field"><label>Vai trò</label><select class="select" name="role"><option value="student" ${role==='student'?'selected':''}>Học sinh</option><option value="teacher" ${role==='teacher'?'selected':''}>Giáo viên</option></select></div></div><div class="form-grid"><div class="field"><label>Username</label><input class="input" name="username" required></div><div class="field"><label>PIN/Mật khẩu ban đầu</label><input class="input" name="password" value="123456" required></div></div><div class="field"><label>Lớp (nếu là học sinh)</label><select class="select" name="classId"><option value="">-- Chưa gán --</option>${(state.data.classes||[]).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><button class="btn btn-primary">Tạo tài khoản</button></form>`);$('#mform').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await rpc('admin.createUser',f);closeModal();toast('Đã tạo tài khoản');await bootstrap(true)}catch(x){toast(x.message,'error')}}}
function openCreateSubject(){modal(`<form id="mform" class="grid"><div class="field"><label>Tên môn</label><input class="input" name="name" required placeholder="Toán"></div><button class="btn btn-primary">Thêm môn</button></form>`);$('#mform').onsubmit=async e=>{e.preventDefault();try{await rpc('admin.createSubject',Object.fromEntries(new FormData(e.target)));closeModal();await bootstrap(true);toast('Đã thêm môn')}catch(x){toast(x.message,'error')}}}
async function resetPassword(id,username){const p=prompt(`Nhập PIN/mật khẩu mới cho ${username}:`,'123456');if(!p)return;try{await rpc('admin.resetPassword',{userId:id,password:p});toast('Đã đặt mật khẩu mới')}catch(e){toast(e.message,'error')}}

// TEACHER
function renderTeacher(){const nav=[{id:'assignments',icon:'📚',label:'Mục Lục & Giao Bài'},{id:'announcements',icon:'📣',label:'Thông Báo'},{id:'individual',icon:'👤',label:'Thi Đua Cá Nhân'},{id:'group',icon:'👥',label:'Thi Đua Tổ'},{id:'report',icon:'📊',label:'Báo Cáo'}];let content='';if(state.activeTab==='assignments')content=teacherAssignments();if(state.activeTab==='announcements')content=teacherAnnouncements();if(state.activeTab==='individual')content=teacherIndividual();if(state.activeTab==='group')content=teacherGroup();if(state.activeTab==='report')content=teacherReport();app().innerHTML=`<div class="app-shell">${header(state.user.displayName,`Bảng điều khiển · ${classSelect()}`,nav)}<main><div class="container">${content}</div></main></div>`}
function cd(){return state.data.classData||{students:[],subjects:[],assignments:[],announcements:[],stats:{}}}
function teacherAssignments(){const d=cd();if(state.selectedSubjectId)return teacherSubjectDetail(d);return `<div class="section-title"><div><h2>📚 Mục Lục Môn Học</h2><p>Chọn một môn để giao bài hoặc xem bài tập đã giao.</p></div></div><div class="subject-grid">${d.subjects.map(s=>{const n=d.assignments.filter(a=>a.subjectId===s.id).length;return `<button class="subject-card" onclick="chooseSubject('${s.id}')"><div class="subject-icon">📁</div><h3>${esc(s.name)}</h3><p>${n} Phiếu bài tập</p></button>`}).join('')||'<div class="card muted">Admin chưa phân môn cho giáo viên ở lớp này.</div>'}</div>`}
function chooseSubject(id){state.selectedSubjectId=id;renderTeacher()}
function teacherSubjectDetail(d){const s=d.subjects.find(x=>x.id===state.selectedSubjectId);const tasks=d.assignments.filter(a=>a.subjectId===state.selectedSubjectId);return `<div class="section-title"><div><button class="btn btn-soft" onclick="state.selectedSubjectId=null;renderTeacher()">← Mục lục</button><h2 style="margin-top:10px">Quản Lý Giao Bài Môn ${esc(s?.name||'')}</h2></div><button class="btn btn-primary" onclick="openCreateAssignment('${state.selectedSubjectId}')">＋ Tạo nhiệm vụ</button></div><div class="list">${tasks.map(t=>`<div class="list-item"><div><span class="pill blue">${esc(s?.name||'')}</span><h3 style="margin:7px 0 3px">${esc(t.title)}</h3><p class="small muted" style="margin:0">Hạn: ${t.dueAt?new Date(t.dueAt).toLocaleString('vi-VN'):'Không đặt'} · Đã nộp ${t.submissionCount||0}</p></div><button class="btn btn-success" onclick="openGrading('${t.id}')">📥 Chấm bài</button></div>`).join('')||'<div class="card center muted">Chưa có bài tập.</div>'}</div>`}
function openCreateAssignment(subjectId){modal(`<form id="mform" class="grid"><div class="field"><label>Tiêu đề bài tập</label><input class="input" name="title" required></div><div class="field"><label>Hướng dẫn</label><textarea class="textarea" name="content"></textarea></div><div class="form-grid"><div class="field"><label>Hạn nộp</label><input class="input" type="datetime-local" name="dueAt"></div><div class="field"><label>Điểm tối đa</label><input class="input" type="number" name="maxScore" value="10" min="1"></div></div><div class="field"><label>Ảnh/PDF đề bài (tối đa 3 file)</label><input class="input" type="file" id="assignmentFiles" multiple accept="image/*,.pdf"></div><button class="btn btn-primary" data-busy>Giao bài</button></form>`);$('#mform').onsubmit=async e=>{e.preventDefault();setBusy(true);try{const f=Object.fromEntries(new FormData(e.target));const files=Array.from($('#assignmentFiles').files).slice(0,3);let attachmentIds=[];if(files.length)attachmentIds=(await uploadFiles(files,'assignment','new')).map(x=>x.fileId);await rpc('assignment.create',{classId:state.classId,subjectId,title:f.title,content:f.content,dueAt:f.dueAt?new Date(f.dueAt).toISOString():'',maxScore:Number(f.maxScore||10),attachmentIds});closeModal();toast('Đã giao bài');state.data.classData=await rpc('teacher.classData',{classId:state.classId});renderTeacher()}catch(x){toast(x.message,'error')}finally{setBusy(false)}}}
function teacherAnnouncements(){const d=cd();return `<div class="section-title"><div><h2>📣 Thông Báo & Dặn Dò</h2><p>Thông báo hiển thị cho học sinh của lớp hiện tại.</p></div><button class="btn btn-amber" onclick="openAnnouncement()">＋ Thông báo</button></div><div class="list">${d.announcements.map(a=>`<div class="list-item"><div><span class="pill amber">Thông báo</span><h3 style="margin:7px 0 4px">${esc(a.title)}</h3><p class="small muted" style="margin:0">${esc(a.content||'')}</p></div><span class="tiny muted">${new Date(a.createdAt).toLocaleDateString('vi-VN')}</span></div>`).join('')||'<div class="card center muted">Chưa có thông báo.</div>'}</div>`}
function openAnnouncement(){modal(`<form id="mform" class="grid"><div class="field"><label>Tiêu đề</label><input class="input" name="title" required></div><div class="field"><label>Nội dung</label><textarea class="textarea" name="content"></textarea></div><button class="btn btn-amber">Đăng thông báo</button></form>`);$('#mform').onsubmit=async e=>{e.preventDefault();try{await rpc('announcement.create',{classId:state.classId,...Object.fromEntries(new FormData(e.target))});closeModal();state.data.classData=await rpc('teacher.classData',{classId:state.classId});renderTeacher();toast('Đã đăng thông báo')}catch(x){toast(x.message,'error')}}}
const positive=[['Phát biểu đúng',1],['Điểm 9, 10',5],['Tiến bộ',3],['Giúp bạn học',2]],negative=[['Đi học muộn',-2],['Không đồng phục',-2],['Mất trật tự',-2],['Thiếu bài tập',-5]];
function teacherIndividual(){const d=cd();return `<div class="card"><div class="section-title"><div><h2>Thi Đua Cá Nhân</h2><p>${state.selectedStudents.size} học sinh đang chọn</p></div><button class="btn btn-soft" onclick="selectAllStudents()">Chọn tất cả</button></div><div class="points-grid">${d.students.map(s=>`<button class="student-chip ${state.selectedStudents.has(s.id)?'selected':''}" onclick="toggleStudent('${s.id}')"><div class="score">${s.points||0}</div><div class="name">${esc(s.displayName)}</div></button>`).join('')}</div></div>${state.selectedStudents.size?`<div class="bottom-actions"><div class="action-row"><span class="pill blue">Đã chọn ${state.selectedStudents.size}</span>${positive.map(x=>`<button class="mini-action" onclick="addBehavior('${esc(x[0])}',${x[1]},'hoctap')">${esc(x[0])} +${x[1]}</button>`).join('')}${negative.map(x=>`<button class="mini-action negative" onclick="addBehavior('${esc(x[0])}',${x[1]},'nenep')">${esc(x[0])} ${x[1]}</button>`).join('')}</div></div>`:''}`}
function toggleStudent(id){state.selectedStudents.has(id)?state.selectedStudents.delete(id):state.selectedStudents.add(id);renderTeacher()}function selectAllStudents(){state.selectedStudents=new Set(cd().students.map(s=>s.id));renderTeacher()}
async function addBehavior(title,points,category){const ids=[...state.selectedStudents];if(!ids.length)return;try{await rpc('behavior.addBatch',{classId:state.classId,studentIds:ids,title,points,category});state.selectedStudents.clear();state.data.classData=await rpc('teacher.classData',{classId:state.classId});renderTeacher();toast('Đã cập nhật điểm')}catch(e){toast(e.message,'error')}}
function teacherGroup(){const groups={};cd().students.forEach(s=>{const g=s.groupNo||1;groups[g]=(groups[g]||0)+(Number(s.points)||0)});const arr=Object.entries(groups).sort((a,b)=>b[1]-a[1]);return `<div class="section-title"><div><h2>👥 Bảng Xếp Hạng Tổ</h2></div></div><div class="grid grid-2">${arr.map(([g,p],i)=>`<div class="card"><span class="pill amber">#${i+1}</span><h3>Tổ ${g}</h3><div style="font-size:38px;font-weight:950">${p} <span class="small muted">điểm</span></div></div>`).join('')}</div>`}
function teacherReport(){const sorted=[...cd().students].sort((a,b)=>(b.points||0)-(a.points||0));return `<div class="card"><div class="section-title"><div><h2>🏆 Bảng Vàng Cá Nhân</h2></div></div><div class="list">${sorted.slice(0,10).map((s,i)=>`<div class="list-item"><div style="display:flex;gap:10px;align-items:center"><span class="pill amber">#${i+1}</span><b>${esc(s.displayName)}</b></div><b style="color:var(--blue)">${s.points||0} đ</b></div>`).join('')}</div></div>`}
async function openGrading(assignmentId){try{const data=await rpc('submission.listByAssignment',{classId:state.classId,assignmentId});state.selectedAssignment={id:assignmentId,data};renderGradingModal()}catch(e){toast(e.message,'error')}}
function renderGradingModal(){const a=state.selectedAssignment.data;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal wide"><div class="modal-head"><b>Chấm bài: ${esc(a.assignment.title)}</b><button class="close" onclick="closeModal()">×</button></div><div class="grade-layout"><div class="grade-list">${a.items.map(s=>`<button class="list-item" style="width:100%;border-radius:0;border-width:0 0 1px 0" onclick="selectSubmissionForGrade('${s.id}')"><div><b>${esc(s.studentName)}</b><div class="tiny muted">${new Date(s.submittedAt).toLocaleString('vi-VN')}</div></div><span class="pill ${s.status==='reviewed'?'green':'blue'}">${s.status==='reviewed'?'Đã chấm':'Chờ chấm'}</span></button>`).join('')||'<p class="muted center" style="padding:20px">Chưa có bài nộp.</p>'}</div><div id="gradeMain" class="grade-main"><div class="center muted" style="padding:50px">Chọn học sinh để xem bài.</div></div><div id="gradePanel" class="grade-panel"></div></div></div></div>`)}
async function selectSubmissionForGrade(id){const s=state.selectedAssignment.data.items.find(x=>x.id===id);state.selectedSubmission=s;$('#gradeMain').innerHTML='<div class="skeleton"></div>';try{const files=await rpc('file.getMany',{fileIds:jparse(s.attachmentIds,[]),classId:s.classId,submissionId:s.id});$('#gradeMain').innerHTML=`<div class="file-grid">${files.map(f=>f.mimeType.startsWith('image/')?`<div class="file-preview"><img src="data:${f.mimeType};base64,${f.base64}"></div>`:`<div class="card"><b>${esc(f.name)}</b><p class="small muted">${esc(f.mimeType)}</p></div>`).join('')||'<div class="muted center">Không có ảnh.</div>'}</div>`}catch(e){$('#gradeMain').innerHTML=`<div class="muted">${esc(e.message)}</div>`}$('#gradePanel').innerHTML=`<div class="field"><label>Học sinh</label><b>${esc(s.studentName)}</b></div><div class="field" style="margin-top:14px"><label>Điểm</label><input class="input" id="gradeScore" type="number" step="0.5" min="0" value="${esc(s.score||'')}"></div><div class="field" style="margin-top:12px"><label>Nhận xét</label><textarea class="textarea" id="gradeFeedback">${esc(s.teacherFeedback||'')}</textarea></div><button class="btn btn-primary btn-block" style="margin-top:12px" onclick="saveGrade()">Lưu lời phê</button>`}
async function saveGrade(){const s=state.selectedSubmission;if(!s)return;try{await rpc('submission.grade',{submissionId:s.id,score:$('#gradeScore').value,teacherFeedback:$('#gradeFeedback').value});toast('Đã lưu nhận xét');closeModal();state.data.classData=await rpc('teacher.classData',{classId:state.classId});renderTeacher()}catch(e){toast(e.message,'error')}}

// STUDENT
function renderStudent(){const d=state.data;const nav=[{id:'assignments',icon:'📚',label:'Nhiệm Vụ & Nộp Bài'},{id:'logs',icon:'⭐',label:'Nhật Ký Điểm'}];let content=state.activeTab==='logs'?studentLogs():studentAssignments();app().innerHTML=`<div class="app-shell">${header(state.user.displayName,'Học sinh',nav)}<main><div class="student-container">${content}</div></main></div>`}
function studentAssignments(){const d=state.data;if(state.selectedSubjectId)return studentSubjectDetail();return `${(d.announcements||[]).slice(0,3).map(a=>`<div class="notice" style="margin-bottom:12px"><h3>📣 ${esc(a.title)}</h3><p>${esc(a.content||'')}</p></div>`).join('')}<div class="card" style="margin-bottom:16px"><p class="tiny strong muted" style="text-transform:uppercase">Điểm rèn luyện của con</p><div style="font-size:48px;font-weight:950;color:var(--blue-dark)">${d.student?.points||0} ⭐</div></div><div class="section-title"><div><h2>📚 Chọn Môn Học</h2></div></div><div class="subject-grid">${(d.subjects||[]).map(s=>{const tasks=(d.assignments||[]).filter(a=>a.subjectId===s.id);const missing=tasks.filter(a=>!(d.submissions||[]).some(x=>x.assignmentId===a.id)).length;return `<button class="subject-card" onclick="state.selectedSubjectId='${s.id}';renderStudent()">${missing?`<span class="pill red" style="position:absolute;right:10px;top:10px">${missing}</span>`:''}<div class="subject-icon">📁</div><h3>${esc(s.name)}</h3><p>${tasks.length} nhiệm vụ</p></button>`}).join('')}</div>`}
function studentSubjectDetail(){const d=state.data;const s=d.subjects.find(x=>x.id===state.selectedSubjectId);const tasks=d.assignments.filter(a=>a.subjectId===state.selectedSubjectId);return `<div class="section-title"><div><button class="btn btn-soft" onclick="state.selectedSubjectId=null;renderStudent()">← Môn học</button><h2 style="margin-top:10px">Môn ${esc(s?.name||'')}</h2></div></div><div class="list">${tasks.map(t=>{const sub=d.submissions.find(x=>x.assignmentId===t.id);const late=t.dueAt&&new Date()>new Date(t.dueAt)&&!sub;return `<div class="card card-flat" style="border-color:${late?'#fecaca':'var(--line)'}"><div style="display:flex;justify-content:space-between;gap:10px"><div><span class="pill blue">${esc(s?.name||'')}</span><h3>${esc(t.title)}</h3></div>${sub?'<span class="pill green">Đã nộp</span>':late?'<span class="pill red">Trễ hạn</span>':'<span class="pill amber">Chưa nộp</span>'}</div><p class="small muted">${esc(t.content||'')}</p>${t.dueAt?`<p class="tiny strong ${late?'':'muted'}">Hạn: ${new Date(t.dueAt).toLocaleString('vi-VN')}</p>`:''}${sub?`<div class="notice"><h3>${sub.status==='reviewed'?'⭐ Bài đã được chấm':'✅ Đã nộp bài'}</h3>${sub.status==='reviewed'?`<p><b>${esc(sub.score||'')}/${esc(t.maxScore||10)}</b> · ${esc(sub.teacherFeedback||'')}</p>`:'<p>Đang chờ giáo viên xem bài.</p>'}</div>`:`<div class="field"><label>Chọn ảnh bài làm</label><input class="input" id="files_${t.id}" type="file" multiple accept="image/*,.pdf"><button class="btn btn-primary" style="margin-top:8px" onclick="submitWork('${t.id}')">📷 XÁC NHẬN NỘP BÀI</button></div>`}</div>`}).join('')||'<div class="card center muted">Chưa có bài tập.</div>'}</div>`}
async function submitWork(assignmentId){const input=$(`#files_${assignmentId}`);const files=Array.from(input.files||[]).slice(0,6);if(!files.length){toast('Hãy chọn ít nhất 1 ảnh','error');return}try{setBusy(true);const uploaded=await uploadFiles(files,'submission',assignmentId);await rpc('submission.submit',{assignmentId,attachmentIds:uploaded.map(x=>x.fileId)});toast('Đã nộp bài thành công');state.data=await rpc('bootstrap',{force:true});renderStudent()}catch(e){toast(e.message,'error')}finally{setBusy(false)}}
function studentLogs(){const logs=state.data.behaviorLogs||[];return `<div class="card"><div class="section-title"><div><h2>⭐ Nhật Ký Điểm</h2><p>Hiển thị tối đa 50 mục gần nhất.</p></div></div><div class="list">${logs.map(l=>`<div class="list-item"><div><b>${esc(l.title)}</b><div class="tiny muted">${new Date(l.createdAt).toLocaleString('vi-VN')}</div></div><b style="color:${Number(l.points)>=0?'#059669':'#dc2626'}">${Number(l.points)>0?'+':''}${l.points}</b></div>`).join('')||'<div class="muted center">Chưa có lịch sử điểm.</div>'}</div></div>`}

async function compressImage(file,maxWidth=1100,quality=.72){if(!file.type.startsWith('image/'))return file;return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{let w=img.width,h=img.height;if(w>maxWidth){h=Math.round(h*maxWidth/w);w=maxWidth}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);c.toBlob(b=>resolve(new File([b],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'})),'image/jpeg',quality)};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function toBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)})}
async function uploadFiles(files,context,refId){const prepared=[];for(const f0 of files){const f=await compressImage(f0);prepared.push({name:f.name,mimeType:f.type||'application/octet-stream',base64:await toBase64(f)})}return rpc('file.uploadMany',{classId:state.classId||state.data?.student?.classId||'',context,refId,files:prepared})}

(async function init(){if(state.token){try{await bootstrap()}catch{renderLogin()}}else renderLogin()})();
